# golang:1.25-alpine
FROM docker.io/library/golang@sha256:1ae0735f00daffa3aaf1363a5184c0d2dc55c78e3db4ec70241cdac97bf84b59 AS builder

WORKDIR /src
COPY go.mod main.go ./

ENV CGO_ENABLED=0
RUN go build -trimpath -ldflags="-s -w" -o /out/app .

# distroless/static-debian12:nonroot
FROM gcr.io/distroless/static-debian12@sha256:52dcfbabb7457ea47c82f6e13af8c8a4a1d9f7b0145142b3ecab20f2b888411d

LABEL org.opencontainers.image.source="https://github.com/defnotyujine/DevSecOps-Lab"

COPY --from=builder /out/app /app

USER 65532:65532
EXPOSE 8080
ENTRYPOINT ["/app"]
